workflows:
  android-workflow:
    name: ErmoKids Android Build
    max_build_duration: 60
    instance_type: linux_x2

    environment:
      node: 18

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Build Android APK and AAB
        script: |
          cd android
          ./gradlew assembleDebug
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
