workflows:
  ermokids_android_build:
    name: ErmoKids Android Build
    max_build_duration: 60

    environment:
      node: latest
      java: 17

    scripts:
      - name: Check Node version
        script: |
          node -v
          npm -v

      - name: Install dependencies
        script: |
          npm install

      - name: Install Capacitor CLI (compatible)
        script: |
          npm install -D @capacitor/cli@latest

      - name: Build web
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk

