workflows:
  ermokids_android_build:
    name: ErmoKids Android Build (Free)
    max_build_duration: 60
    environment:
      node: 18
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk

